### ISSUE TITLE
unable to convert timeout

### ISSUE THREAD

**Issue by klobuczek** [socketry/async#317]
After upgrading to async 2.12 I'm getting the following error:

```
RuntimeError: unable to convert timeout

  0) Session retries read transaction until success
     Failure/Error: Sync { super(*args, **kwargs, &block) }

     RuntimeError:
       unable to convert timeout
     # /Users/Heinrich_Klobuczek/.rvm/gems/ruby-3.2.0/gems/async-2.12.0/lib/async/scheduler.rb:309:in `select'
     # /Users/Heinrich_Klobuczek/.rvm/gems/ruby-3.2.0/gems/async-2.12.0/lib/async/scheduler.rb:309:in `run_once!'
     # /Users/Heinrich_Klobuczek/.rvm/gems/ruby-3.2.0/gems/async-2.12.0/lib/async/scheduler.rb:283:in `run_once'
     # /Users/Heinrich_Klobuczek/.rvm/gems/ruby-3.2.0/gems/async-2.12.0/lib/async/scheduler.rb:358:in `block in run'
     # /Users/Heinrich_Klobuczek/.rvm/gems/ruby-3.2.0/gems/async-2.12.0/lib/async/scheduler.rb:352:in `handle_interrupt'
     # /Users/Heinrich_Klobuczek/.rvm/gems/ruby-3.2.0/gems/async-2.12.0/lib/async/scheduler.rb:352:in `run'
     # /Users/Heinrich_Klobuczek/.rvm/gems/ruby-3.2.0/gems/async-2.12.0/lib/kernel/sync.rb:26:in `Sync'
     # ./lib/neo4j/driver/synchronizable.rb:16:in `block (3 levels) in with_sync_wrapper'
     # ./spec/integration/session_spec.rb:77:in `block (2 levels) in <top (required)>'
     # ./spec/support/neo4j_cleaner.rb:12:in `cleaning'
     # ./spec/spec_helper.rb:36:in `block (2 levels) in <top (required)>'
```

The same spec works with 2.11. Please have a look if this rings a bell or ask me for further troubleshooting. I would be more than happy to help getting to the bottom of it. I'm using ruby 3.2.0.

**Comment by ioquatix** [comment]
Hmm, thanks for this report, I have an idea what is going on.

**Comment by ioquatix** [comment]
I've released `io-event` v1.6.1 with <https://github.com/socketry/io-event/pull/104> which should include what the duration value is. Do you mind updating and running your test again? The error message should be more descriptive.

**Comment by klobuczek** [comment]
I'm including now the entire rspec preamble which I did not include before although the same warnings were present in the previous version as well.
```
/bin/bash -c "/Users/Heinrich_Klobuczek/.rvm/bin/rvm ruby-3.2.0 do /Users/Heinrich_Klobuczek/.rvm/rubies/ruby-3.2.0/bin/ruby -x /Users/Heinrich_Klobuczek/.rvm/gems/ruby-3.2.0/bin/bundle exec /Users/Heinrich_Klobuczek/.rvm/rubies/ruby-3.2.0/bin/ruby /Users/Heinrich_Klobuczek/.rvm/gems/ruby-3.2.0/bin/rspec /Users/Heinrich_Klobuczek/mck/neo4j-ruby-driver/spec/integration/session_spec.rb --require teamcity/spec/runner/formatter/teamcity/formatter --format Spec::Runner::Formatter::TeamcityFormatter"
Testing started at 06:09 ...
/Users/Heinrich_Klobuczek/.rvm/gems/ruby-3.2.0/gems/io-event-1.6.2/lib/io/event/support.rb:27: warning: IO::Buffer is experimental and both the Ruby and C interface may change in the future!
Fiber#storage has borked keys and is being monkey-patched.
Run options: exclude {:concurrency=>true, :version=>#<Method: Object(DriverHelper::Helper)#not_version?(requirement) ./spec/support/driver_helper.rb:46>, :auth=>:none}

ArgumentError: unable to convert timeout: 0.7999849999323487 seconds

  0) Session retries read transaction until success
     Failure/Error: Sync { super(*args, **kwargs, &block) }

     ArgumentError:
       unable to convert timeout: 0.7999849999323487 seconds
     # /Users/Heinrich_Klobuczek/.rvm/gems/ruby-3.2.0/gems/async-2.12.0/lib/async/scheduler.rb:309:in `select'
     # /Users/Heinrich_Klobuczek/.rvm/gems/ruby-3.2.0/gems/async-2.12.0/lib/async/scheduler.rb:309:in `run_once!'
     # /Users/Heinrich_Klobuczek/.rvm/gems/ruby-3.2.0/gems/async-2.12.0/lib/async/scheduler.rb:283:in `run_once'
     # /Users/Heinrich_Klobuczek/.rvm/gems/ruby-3.2.0/gems/async-2.12.0/lib/async/scheduler.rb:358:in `block in run'
     # /Users/Heinrich_Klobuczek/.rvm/gems/ruby-3.2.0/gems/async-2.12.0/lib/async/scheduler.rb:352:in `handle_interrupt'
     # /Users/Heinrich_Klobuczek/.rvm/gems/ruby-3.2.0/gems/async-2.12.0/lib/async/scheduler.rb:352:in `run'
     # /Users/Heinrich_Klobuczek/.rvm/gems/ruby-3.2.0/gems/async-2.12.0/lib/kernel/sync.rb:26:in `Sync'
     # ./lib/neo4j/driver/synchronizable.rb:16:in `block (3 levels) in with_sync_wrapper'
     # ./spec/integration/session_spec.rb:77:in `block (2 levels) in <top (required)>'
     # ./spec/support/neo4j_cleaner.rb:12:in `cleaning'
     # ./spec/spec_helper.rb:36:in `block (2 levels) in <top (required)>'
```
