### ISSUE TITLE
ret: 2, hash modified during iteration during utopia specs

### ISSUE THREAD

**Issue by ioquatix** [socketry/async#57]
```
1 samples: 1x 200. 1691.74 requests per second. S/D: 0.000µs.
  should be responsive (FAILED - 1)

Failures:

  1) website should be responsive
     Failure/Error: @hash.each_key(&block)
     
     RuntimeError:
       ret: 2, hash modified during iteration
     # /home/samuel/.rbenv/versions/2.7.0/lib/ruby/2.7.0/set.rb:328:in `each_key'
     # /home/samuel/.rbenv/versions/2.7.0/lib/ruby/2.7.0/set.rb:328:in `each'
     # /home/samuel/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/async-1.24.2/lib/async/task.rb:248:in `stop!'
     # /home/samuel/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/async-1.24.2/lib/async/task.rb:262:in `rescue in block in make_fiber'
     # /home/samuel/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/async-1.24.2/lib/async/task.rb:261:in `block in make_fiber'
     # ------------------
     # --- Caused by: ---
     # Async::Stop:
     #   Async::Stop
     #   /home/samuel/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/async-1.24.2/lib/async/task.rb:66:in `yield'

Finished in 0.12239 seconds (files took 0.52634 seconds to load)
1 example, 1 failure
```
